name: terraform apply
on:
  push:
    branches:
      - master
defaults:
  run:
    shell: bash
jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    steps:
    - name: Setup AWS Credentials
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        mkdir -p .aws
        echo [default] > .aws/credentials
        echo aws_access_key_id = $AWS_ACCESS_KEY_ID >> .aws/credentials
        echo aws_secret_access_key = $AWS_SECRET_ACCESS_KEY >> .aws/credentials
    - uses: hashicorp/setup-terraform@v1
    - name: Terraform version
      run: terraform version
    - name: Terraform Init
      run: terraform init
