name: terraform apply
on:
  push:
    branches:
      - master
defaults:
  run:
    shell: bash
jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Terraform
      uses: ./
    - name: Terraform Init
      run: terraform init

